### ISSUE TITLE
About reproducing RTSS 2020 paper "DAG Scheduling and Analysis on Multiprocessor Systems"

### ISSUE THREAD

**Issue by ita9naiwa** [automaticdai/dag-gen-rnd#15]
Hi, I'm Hyunsung Lee and reproducing your work on RTSS 2020 titled DAG Scheduling and Analysis on Multiprocessor Systems.

I am really fascinated by your work and motivated to do some stuff upon your framework and works.

I used this repo to create the dataset, ran experiments with your code provided at another repository.
And I found slightly different results from your original paper and checked your implementation on `daggen.py` don't get some arguments. For example,

https://github.com/automaticdai/dag-gen-rnd/blob/a5babed6cb88bf629af5990cc544f2458b6fec38/src/rnddag.py#L201

I think the minimum value of parallelism must be 2 to follow your instruction on your work.

I think this is the only difference between your implementation here and the experiment environment on your paper, but I am not very sure.

Is there any other misalignment or things that should be manually modified between your work and this dag gen library?

Thanks,
Hyunsung

**Comment by automaticdai** [comment]
Dear Hyunsung, 

Thanks for your interest in our work.
Yes, I think you are right, the minimal parallelsim should be 2.
This work is indepedently developed so the changed version might cause inconsistent. However, if you do need to reproduce the work, I have pre-generated dataset that we used in the RTSS paper.
Please give me you email address if you need it and I will share it to you.

Regards,
Steven

**Comment by ita9naiwa** [comment]
Thanks for your clarification. 

I just wanted to check the validity of the task generation code and my scheduling algorithm implementation and both yours and mine show identical results so it's fine even they ran on a different dataset.

Thanks for your clarification.
Hyunsung

**Comment by automaticdai** [comment]
No problem. Let me know if you have further questions.

Steven
